const DB_NAME='hotaru-data-cache', DB_VERSION=1, STORE='entries';
const DB_OPEN_TIMEOUT_MS=1200, TX_TIMEOUT_MS=1500;
function timeoutError(label){return new Error(`${label} timed out`)}
function withTimeout(promise,ms,label){let timer;return Promise.race([promise,new Promise((_,reject)=>{timer=setTimeout(()=>reject(timeoutError(label)),ms)})]).finally(()=>clearTimeout(timer))}
function openDB(){return withTimeout(new Promise((resolve,reject)=>{if(!('indexedDB'in window))return reject(new Error('IndexedDB unavailable'));const req=indexedDB.open(DB_NAME,DB_VERSION);let settled=false;const done=(fn,value)=>{if(settled)return;settled=true;fn(value)};req.onupgradeneeded=()=>{const db=req.result;if(!db.objectStoreNames.contains(STORE))db.createObjectStore(STORE)};req.onsuccess=()=>done(resolve,req.result);req.onerror=()=>done(reject,req.error||new Error('IndexedDB open failed'));req.onblocked=()=>done(reject,new Error('IndexedDB open blocked'))}),DB_OPEN_TIMEOUT_MS,'IndexedDB open')}
async function runTransaction(mode,operation){const db=await openDB();try{return await withTimeout(new Promise((resolve,reject)=>{let settled=false;const tx=db.transaction(STORE,mode),store=tx.objectStore(STORE);const finish=(fn,value)=>{if(settled)return;settled=true;fn(value)};try{operation(store,finish)}catch(error){finish(reject,error);return}tx.oncomplete=()=>finish(resolve,undefined);tx.onerror=()=>finish(reject,tx.error||new Error('IndexedDB transaction failed'));tx.onabort=()=>finish(reject,tx.error||new Error('IndexedDB transaction aborted'))}),TX_TIMEOUT_MS,'IndexedDB transaction')}finally{try{db.close()}catch{}}}
export async function cacheGet(key){try{const db=await openDB();try{return await withTimeout(new Promise((resolve,reject)=>{let settled=false;const tx=db.transaction(STORE,'readonly'),req=tx.objectStore(STORE).get(key);const finish=(fn,value)=>{if(settled)return;settled=true;fn(value)};req.onsuccess=()=>finish(resolve,req.result??null);req.onerror=()=>finish(reject,req.error||new Error('IndexedDB read failed'));tx.onerror=()=>finish(reject,tx.error||new Error('IndexedDB read transaction failed'));tx.onabort=()=>finish(reject,tx.error||new Error('IndexedDB read transaction aborted'))}),TX_TIMEOUT_MS,'IndexedDB read')}finally{try{db.close()}catch{}}}catch{return null}}
export async function cacheSet(key,value){try{await runTransaction('readwrite',(store,finish)=>{const req=store.put(value,key);req.onerror=()=>finish(()=>{},undefined)})}catch{}}
export async function cacheDelete(key){try{await runTransaction('readwrite',(store,finish)=>{const req=store.delete(key);req.onerror=()=>finish(()=>{},undefined)})}catch{}}
