const STAT_LABELS={cr:'CRIT Rate',cd:'CRIT DMG',er:'Energy Recharge',em:'Elemental Mastery',hp:'HP',atk:'ATK',def:'DEF',hpPct:'HP%',atkPct:'ATK%',defPct:'DEF%'};
function textOf(detail){return[detail?.description,...(detail?.skills||[]).flatMap(x=>[x.name,x.description]),...(detail?.passives||[]).flatMap(x=>[x.name,x.description]),...(detail?.constellations||[]).flatMap(x=>[x.name,x.description])].filter(Boolean).join(' ').toLowerCase()}
function count(text,phrases){return phrases.reduce((sum,phrase)=>sum+(text.match(new RegExp(phrase,'g'))||[]).length,0)}
function inferEnergyCost(detail){const rawText=JSON.stringify(detail?.raw||{}),matches=[...rawText.matchAll(/Energy Cost[^0-9]{0,20}([0-9]{2,3})/gi)],values=matches.map(m=>Number(m[1])).filter(n=>n>=20&&n<=100);return values.length?Math.max(...values):60}

export function inferBuildProfile(detail={}){
  const text=textOf(detail),hp=count(text,['based on max hp','max hp','hp%']),def=count(text,['based on def','defense','\\bdef\\b']),em=count(text,['elemental mastery','reaction dmg','reaction damage']),atk=count(text,['based on atk','attack stat','\\batk\\b']);
  let scaling='ATK';if(hp>Math.max(atk,def,em))scaling='HP';else if(def>Math.max(atk,hp,em))scaling='DEF';else if(em>Math.max(atk,hp,def))scaling='EM';
  const heal=count(text,['heal','healing']),shield=count(text,['shield']),summon=count(text,['summon','off-field','not on the field','nearby opponents at intervals']),normal=count(text,['normal attack']),charged=count(text,['charged attack']),plunge=count(text,['plunging attack','plunge']),skill=count(text,['elemental skill','skill dmg','skill damage']),burst=count(text,['elemental burst','burst dmg','burst damage']);
  let role='On-field DPS';if(heal>=3)role='Healer / Support';else if(shield>=2&&skill>=normal)role='Shielder / Support';else if(summon>=2)role='Off-field DPS / Support';else if(burst>skill+normal)role='Burst DPS';else if(skill>normal+charged)role='Skill DPS';
  const focusScores={'Normal Attack':normal,'Charged Attack':charged,'Plunging Attack':plunge,'Elemental Skill':skill,'Elemental Burst':burst},focus=Object.entries(focusScores).sort((a,b)=>b[1]-a[1])[0]?.[0]||'Elemental Skill',energyCost=inferEnergyCost(detail),reactionDriven=em>=2,support=/support|healer|shielder/i.test(role);
  const mainStats={sands:energyCost>=70?[`ER%`,`${scaling}%`]:[`${scaling}%`,'ER%'],goblet:support&&scaling!=='ATK'?[`${scaling}%`,`${detail.element||'Elemental'} DMG%`]:[`${detail.element||'Elemental'} DMG%`,`${scaling}%`],circlet:heal>=3?['Healing Bonus',`${scaling}%`,'CRIT Rate / CRIT DMG']:['CRIT Rate / CRIT DMG',`${scaling}%`]};
  const priorities=['ER'];if(!support||/dps/i.test(role))priorities.push('CRIT Rate','CRIT DMG');if(reactionDriven)priorities.push('Elemental Mastery');priorities.push(`${scaling}%`);if(support&&!reactionDriven)priorities.push('CRIT Rate');
  const profile={role,scaling,focus,energyCost,reactionDriven,mainStats,substats:[...new Set(priorities)],confidence:Math.min(95,55+Math.min(40,hp+def+em+atk+heal+shield+skill+burst))};profile.targets=statTargets(profile,{});return profile
}
export function statTargets(profile,context={}){
  const sameElement=Math.max(0,Number(context.sameElement||0)),favonius=Math.max(0,Number(context.favonius||0));let erGood=profile.energyCost>=80?180:profile.energyCost>=70?165:profile.energyCost>=60?145:125;erGood-=Math.min(30,sameElement*12);erGood-=Math.min(20,favonius*8);erGood=Math.max(110,erGood);
  const support=/support|healer|shielder/i.test(profile.role),crit=support&&!/dps/i.test(profile.role)?{cr:[30,45,60],cd:[60,90,120]}:{cr:[50,65,75],cd:[100,140,180]};
  return{cr:{min:crit.cr[0],good:crit.cr[1],great:crit.cr[2],unit:'%'},cd:{min:crit.cd[0],good:crit.cd[1],great:crit.cd[2],unit:'%'},er:{min:Math.max(100,erGood-20),good:erGood,great:erGood+20,unit:'%'},em:profile.reactionDriven?{min:100,good:250,great:450,unit:''}:{min:0,good:80,great:160,unit:''}}
}
function normalizeSubstat(value=''){const t=String(value).toLowerCase();if(t.includes('crit rate'))return'cr';if(t.includes('crit dmg')||t.includes('critical hurt'))return'cd';if(t.includes('recharge')||t.includes('charge efficiency'))return'er';if(t.includes('mastery'))return'em';if(t.includes('hp'))return'hpPct';if(t.includes('def'))return'defPct';if(t.includes('atk')||t.includes('attack'))return'atkPct';return''}
function keywordFit(text,profile){const t=String(text||'').toLowerCase();let score=0;if(t.includes('crit'))score+=/dps/i.test(profile.role)?16:7;if(t.includes('energy')||t.includes('recharge'))score+=profile.energyCost>=60?15:8;if(t.includes('elemental mastery')||t.includes('reaction'))score+=profile.reactionDriven?18:2;if(t.includes('hp'))score+=profile.scaling==='HP'?18:2;if(t.includes('def'))score+=profile.scaling==='DEF'?18:1;if(t.includes('atk')||t.includes('attack'))score+=profile.scaling==='ATK'?14:3;if(t.includes('healing'))score+=/healer/i.test(profile.role)?20:1;if(t.includes('shield'))score+=/shielder/i.test(profile.role)?20:1;const focus=profile.focus.toLowerCase();if(focus.includes('skill')&&t.includes('skill'))score+=22;if(focus.includes('burst')&&t.includes('burst'))score+=22;if(focus.includes('normal')&&t.includes('normal attack'))score+=20;if(focus.includes('charged')&&t.includes('charged attack'))score+=20;if(focus.includes('plung')&&(t.includes('plung')||t.includes('plunge')))score+=20;if(/off-field/i.test(profile.role)&&(t.includes('off-field')||t.includes('not on the field')))score+=24;return score}
export function scoreWeapon(weapon,profile){if(!weapon)return{score:0,reasons:[]};let score=Math.min(18,Number(weapon.rarity||1)*3);const reasons=[],stat=normalizeSubstat(weapon.subStat||weapon.substat||''),desired=profile.substats.map(normalizeSubstat);if(stat&&desired.includes(stat)){const bonus=stat==='er'&&profile.energyCost>=70?25:(stat==='cr'||stat==='cd')?24:18;score+=bonus;reasons.push(`${weapon.subStat} supports this build.`)}const passiveText=`${weapon.passiveName||''} ${weapon.passiveDesc||weapon.description||''}`,fit=Math.min(40,keywordFit(passiveText,profile));score+=fit;if(fit>=20)reasons.push(`Passive aligns with ${profile.focus.toLowerCase()} / ${profile.role.toLowerCase()}.`);if(!reasons.length)reasons.push('Usable stat stick; verify against your exact rotation and team.');return{score:Math.min(100,Math.round(score)),reasons}}
export function rankWeapons(weapons=[],profile,ownedNames=[]){const owned=new Set(ownedNames.map(x=>String(x).toLowerCase()));return weapons.map(w=>{const result=scoreWeapon(w,profile);return{...w,hotaruScore:result.score,hotaruReasons:result.reasons,owned:owned.has(String(w.name).toLowerCase())}}).sort((a,b)=>(b.owned-a.owned)||b.hotaruScore-a.hotaruScore||b.rarity-a.rarity).slice(0,10)}
export function scoreArtifactSet(set,profile){const text=`${set?.twoPiece||''} ${set?.fourPiece||''}`;let score=keywordFit(text,profile);if(String(set?.fourPiece||'').trim())score+=8;if(String(set?.twoPiece||'').trim())score+=4;return Math.min(100,Math.round(score))}
export function rankArtifactSets(sets=[],profile){return sets.map(set=>({...set,hotaruScore:scoreArtifactSet(set,profile)})).sort((a,b)=>b.hotaruScore-a.hotaruScore||a.name.localeCompare(b.name)).slice(0,8)}
function band(value,target){if(!Number.isFinite(value))return{state:'unknown',label:'Not entered',points:0};if(value>=target.great)return{state:'great',label:'Great',points:25};if(value>=target.good)return{state:'good',label:'Good',points:21};if(value>=target.min)return{state:'ok',label:'Usable',points:16};return{state:'low',label:'Below target',points:Math.max(3,Math.round(15*value/Math.max(1,target.min)))}}
export function evaluateBuild({profile,stats={},mainStats={},context={},weapon=null,artifactSet=null}){
  const targets=statTargets(profile,context),checks={cr:band(Number(stats.cr),targets.cr),cd:band(Number(stats.cd),targets.cd),er:band(Number(stats.er),targets.er),em:band(Number(stats.em),targets.em)},damageRole=/dps/i.test(profile.role),statWeightKeys=damageRole?['cr','cd','er']:['er','cr','cd'];if(profile.reactionDriven)statWeightKeys.push('em');let statPoints=statWeightKeys.reduce((sum,key)=>sum+checks[key].points,0);statPoints=statPoints/(statWeightKeys.length*25)*55;
  const sands=String(mainStats.sands||'').toLowerCase(),goblet=String(mainStats.goblet||'').toLowerCase(),circlet=String(mainStats.circlet||'').toLowerCase();let mainPoints=0;
  if(profile.mainStats.sands.some(x=>sands&&x.toLowerCase().replace('%','').includes(sands.replace('%',''))||sands&&sands.includes(x.toLowerCase().replace('%',''))))mainPoints+=7;
  if(profile.mainStats.goblet.some(x=>goblet&&x.toLowerCase().replace('%','').includes(goblet.replace('%',''))||goblet&&goblet.includes(x.toLowerCase().replace('%',''))))mainPoints+=7;
  if(profile.mainStats.circlet.some(x=>circlet&&x.toLowerCase().includes(circlet)||circlet&&circlet.includes(x.toLowerCase().replace('%','').split(' / ')[0])))mainPoints+=6;
  const weaponPoints=weapon?scoreWeapon(weapon,profile).score*.15:0,artifactPoints=artifactSet?scoreArtifactSet(artifactSet,profile)*.10:0,total=Math.round(Math.min(100,statPoints+mainPoints+weaponPoints+artifactPoints)),issues=[];
  if(checks.er.state==='low')issues.push({priority:1,stat:'Energy Recharge',message:`Raise ER toward ~${targets.er.good}% for the selected team context.`});
  if(damageRole&&checks.cr.state==='low')issues.push({priority:2,stat:'CRIT Rate',message:`Raise CRIT Rate toward ${targets.cr.good}% before chasing more CRIT DMG.`});
  if(damageRole&&checks.cd.state==='low')issues.push({priority:3,stat:'CRIT DMG',message:`CRIT DMG is below Hotaru's general ${profile.role} target.`});
  if(profile.reactionDriven&&checks.em.state==='low')issues.push({priority:2,stat:'Elemental Mastery',message:`This kit appears reaction-driven; add EM toward ${targets.em.good}.`});
  if(mainPoints<14)issues.push({priority:2,stat:'Main stats',message:'One or more artifact main stats do not match the inferred build profile.'});issues.sort((a,b)=>a.priority-b.priority);
  const grade=total>=90?'Excellent':total>=78?'Strong':total>=65?'Good':total>=50?'Developing':'Needs work';
  return{score:total,grade,targets,checks,mainStatPoints:mainPoints,biggestImprovement:issues[0]?.message||'No major issue detected by the general build rules. Fine-tune with character-specific theorycrafting.',issues}
}
export function scoreArtifact({profile,mainStat='',substats={},context={}}){const targets=statTargets(profile,context),desiredMain=[...profile.mainStats.sands,...profile.mainStats.goblet,...profile.mainStats.circlet].map(x=>x.toLowerCase().replace('%',''));let score=desiredMain.some(x=>String(mainStat).toLowerCase().includes(x.split(' / ')[0]))?20:7;const cr=Number(substats.cr||0),cd=Number(substats.cd||0),er=Number(substats.er||0),em=Number(substats.em||0),scaling=Number(substats.scaling||0);score+=Math.min(35,cr*2+cd);score+=Math.min(18,er*(profile.energyCost>=70?.9:.55));if(profile.reactionDriven)score+=Math.min(15,em/4);score+=Math.min(12,scaling*.8);score=Math.round(Math.min(100,score));return{score,grade:score>=85?'Excellent':score>=70?'Very good':score>=55?'Good':score>=40?'Usable':'Low priority',critValue:Number((cr*2+cd).toFixed(1)),note:er<Math.max(0,targets.er.good-120)&&profile.energyCost>=70?'ER rolls may be more valuable than additional CRIT until the build reaches its team ER target.':'Evaluate this piece in the context of the full build, not by CRIT Value alone.'}}
export const labels=STAT_LABELS;
