import { buildMapUrl, loadMapState, saveMapState, normalizeMarkerNames } from './interactive-map.js';

const REGIONS=['Mondstadt','Liyue','Inazuma','Sumeru','Fontaine','Natlan','Nod-Krai','Snezhnaya'];
const OCULI={Mondstadt:'Anemoculus',Liyue:'Geoculus',Inazuma:'Electroculus',Sumeru:'Dendroculus',Fontaine:'Hydroculus',Natlan:'Pyroculus','Nod-Krai':'Cryoculus',Snezhnaya:'Cryoculus'};
function esc(value=''){return String(value||'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function shrine(region){return region==='Inazuma'?'Inazuma Shrine of Depths':`${region} Shrine of Depths`}
function markers(region){return[{label:'Shrines of Depths',name:shrine(region),kind:'Permanent exploration'},{label:'Oculi',name:OCULI[region]||'Oculi',kind:'Collectible'},{label:'Teleport Waypoints',name:'Teleport Waypoint',kind:'Navigation'},{label:'Statues',name:'Statue of The Seven',kind:'Navigation'},{label:'Domains',name:'Domain',kind:'Farming'},{label:'World Quests',name:'World Quests',kind:'Quest'}]}
function apply(names){const view=document.getElementById('hotaru-map-view'),frame=view?.querySelector('.hotaru-map-frame');if(!frame)return;const values=normalizeMarkerNames(names),state=loadMapState();state.names=values;state.browseAll=false;state.lastOpenedAt=new Date().toISOString();saveMapState(state);frame.src=buildMapUrl(values);const label=view.querySelector('.hotaru-map-current span');if(label)label.textContent=values.join(', ')}
function render(region){return`<div class="hotaru-explore-grid">${markers(region).map(item=>`<button class="hotaru-explore-card" data-hotaru-explore-marker="${esc(item.name)}"><strong>${esc(item.label)}</strong><span>${esc(item.kind)}</span></button>`).join('')}</div>`}
export function enhanceExplorationGuide(){const view=document.getElementById('hotaru-map-view');if(!view||document.getElementById('hotaru-exploration-guide'))return;const toolbar=view.querySelector('.hotaru-map-toolbar')||view.querySelector('.section');if(!toolbar)return;const section=document.createElement('section');section.id='hotaru-exploration-guide';section.className='section card hotaru-reference-card';section.innerHTML=`<div class="section-head"><div><div class="eyebrow">Exploration guide</div><h2>Region locations</h2></div><label class="field hotaru-explore-region"><span>Region</span><select id="hotaru-explore-region">${REGIONS.map(x=>`<option>${esc(x)}</option>`).join('')}</select></label></div><div id="hotaru-explore-cards">${render(REGIONS[0])}</div><p class="muted small">Use these shortcuts for Shrines of Depths, Oculi, waypoints, domains and quests. Hotaru opens live provider-maintained map markers instead of copying third-party route screenshots.</p>`;toolbar.after(section)}

document.addEventListener('change',event=>{if(event.target?.id!=='hotaru-explore-region')return;const root=document.getElementById('hotaru-explore-cards');if(root)root.innerHTML=render(event.target.value)},false);
document.addEventListener('click',event=>{const button=event.target.closest('[data-hotaru-explore-marker]');if(!button)return;event.preventDefault();apply([button.dataset.hotaruExploreMarker]);document.getElementById('hotaru-exploration-guide')?.scrollIntoView({block:'start',behavior:'smooth'})},false);
