import { MAP_BROWSE_URL, buildMapUrl, loadMapState, saveMapState, normalizeMarkerNames } from './interactive-map.js';

const REGIONS=['Mondstadt','Liyue','Inazuma','Sumeru','Fontaine','Natlan','Nod-Krai','Snezhnaya'];
const OCULI={Mondstadt:'Anemoculus',Liyue:'Geoculus',Inazuma:'Electroculus',Sumeru:'Dendroculus',Fontaine:'Hydroculus',Natlan:'Pyroculus'};
const PROVIDER_BROWSE_REGIONS=new Set(['Nod-Krai','Snezhnaya']);
function esc(value=''){return String(value||'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function shrine(region){return region==='Inazuma'?'Inazuma Shrine of Depths':`${region} Shrine of Depths`}
function markers(region){const browse=PROVIDER_BROWSE_REGIONS.has(region);return[{label:'Shrines of Depths',name:browse?'':shrine(region),browse,kind:browse?'Browse provider filters':'Permanent exploration'},{label:'Oculi',name:browse?'':(OCULI[region]||'Oculi'),browse,kind:browse?'Browse provider filters':'Collectible'},{label:'Teleport Waypoints',name:'Teleport Waypoint',kind:'Navigation'},{label:'Statues',name:'Statue of The Seven',kind:'Navigation'},{label:'Domains',name:'Domain',kind:'Farming'},{label:'World Quests',name:'World Quests',kind:'Quest'}]}
function apply(names){const view=document.getElementById('hotaru-map-view'),frame=view?.querySelector('.hotaru-map-frame');if(!frame)return;const values=normalizeMarkerNames(names),state=loadMapState();state.names=values;state.browseAll=false;state.lastOpenedAt=new Date().toISOString();saveMapState(state);frame.src=buildMapUrl(values);const label=view.querySelector('.hotaru-map-current span');if(label)label.textContent=values.join(', ')}
function browse(){const view=document.getElementById('hotaru-map-view'),frame=view?.querySelector('.hotaru-map-frame');if(!frame)return;const state=loadMapState();state.names=[];state.browseAll=true;state.lastOpenedAt=new Date().toISOString();saveMapState(state);frame.src=MAP_BROWSE_URL;const label=view.querySelector('.hotaru-map-current span');if(label)label.textContent='Browse all provider filters'}
function render(region){return`<div class="hotaru-explore-grid">${markers(region).map(item=>`<button class="hotaru-explore-card" ${item.browse?'data-hotaru-explore-browse="1"':`data-hotaru-explore-marker="${esc(item.name)}"`}><strong>${esc(item.label)}</strong><span>${esc(item.kind)}</span></button>`).join('')}</div>`}
export function enhanceExplorationGuide(){const view=document.getElementById('hotaru-map-view');if(!view||document.getElementById('hotaru-exploration-guide'))return;const toolbar=view.querySelector('.hotaru-map-toolbar')||view.querySelector('.section');if(!toolbar)return;const section=document.createElement('section');section.id='hotaru-exploration-guide';section.className='section card hotaru-reference-card';section.innerHTML=`<div class="section-head"><div><div class="eyebrow">Exploration guide</div><h2>Region locations</h2></div><label class="field hotaru-explore-region"><span>Region</span><select id="hotaru-explore-region">${REGIONS.map(x=>`<option>${esc(x)}</option>`).join('')}</select></label></div><div id="hotaru-explore-cards">${render(REGIONS[0])}</div><p class="muted small">Use these shortcuts for Shrines of Depths, Oculi, waypoints, domains and quests. For newly released regions whose marker names are not yet documented by the map provider, Hotaru opens the provider-maintained full filter list instead of guessing a broken marker.</p>`;toolbar.after(section)}

document.addEventListener('change',event=>{if(event.target?.id!=='hotaru-explore-region')return;const root=document.getElementById('hotaru-explore-cards');if(root)root.innerHTML=render(event.target.value)},false);
document.addEventListener('click',event=>{const browseButton=event.target.closest('[data-hotaru-explore-browse]');if(browseButton){event.preventDefault();browse();return}const button=event.target.closest('[data-hotaru-explore-marker]');if(!button)return;event.preventDefault();apply([button.dataset.hotaruExploreMarker]);document.getElementById('hotaru-exploration-guide')?.scrollIntoView({block:'start',behavior:'smooth'})},false);
