import { loadCharacterReference } from '../data/character-reference.js';
import { hydrateWeaponCandidates } from '../data/game-data.js';
import { rankWeapons, rankArtifactSets, statTargets } from './build-engine.js';
import { ascensionTotals, talentTotals } from './farming.js';
import { fallbackItemIcon, fallbackWeaponIcon, fallbackArtifactIcon, fallbackCharacterIcon, materialSourceNames, safeCharacterRarity } from './content-media.js';
import { guideExplorationMarkers } from '../data/map-registry.js';
import { referenceStats, roleRatings, talentPriority, constellationList, constellationRating, inferTalentBookSchedule, ascensionStages, weaponAcquisition, sampleTeams, notableTeammates, extractVoiceActors, guideBuildVariants, stripMarkup } from './guide-engine.js';

const HAKUSH_UI='https://static.nanoka.cc/gi/UI';
let activeCharacter='',reference=null,weaponPromise=null;
const esc=value=>String(value??'').replace(/[&<>'\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));

function insertBeforeActions(app,node){const actions=[...app.querySelectorAll('main > .section.grid.two')].at(-1);if(actions)actions.before(node);else app.querySelector('main')?.appendChild(node)}
function sourceAttr(values=[]){return esc(JSON.stringify([...new Set(values.map(value=>String(value||'').trim()).filter(Boolean))]))}
function img(src,alt,cls='',fallbacks=[]){const sources=[...new Set([src,...fallbacks].map(value=>String(value||'').trim()).filter(Boolean))];if(!sources.length)return`<div class="hotaru-guide-placeholder ${cls}">✦</div>`;return`<img class="${cls}" src="${esc(sources[0])}" data-hotaru-sources="${sourceAttr(sources)}" data-hotaru-source-index="0" alt="${esc(alt)}" loading="lazy" decoding="async" onerror="const s=JSON.parse(this.dataset.hotaruSources||'[]'),i=Number(this.dataset.hotaruSourceIndex||0)+1;if(i<s.length){this.dataset.hotaruSourceIndex=String(i);this.src=s[i]}else{this.hidden=true;this.nextElementSibling?.removeAttribute('hidden')}"><span class="hotaru-guide-placeholder ${cls}" hidden>✦</span>`}
function itemIcon(name,src=''){const stable=fallbackItemIcon(name);return img(stable||src,name,'hotaru-guide-item-icon',stable&&src?[src]:[])}
function characterIcon(character){const stable=fallbackCharacterIcon(character?.slug||character?.name);return img(stable||character?.icon,character?.name||'Character','hotaru-guide-avatar',stable&&character?.icon?[character.icon]:[])}
function artifactIcon(set){const stable=fallbackArtifactIcon(set?.name);return img(stable||set?.icon,set?.name||'Artifact','hotaru-guide-item-icon',stable&&set?.icon?[set.icon]:[])}
function weaponIcon(weapon){const stable=fallbackWeaponIcon(weapon?.slug||weapon?.name);return img(stable||weapon?.icon,weapon?.name||'Weapon','hotaru-guide-item-icon',stable&&weapon?.icon?[weapon.icon]:[])}
function materialIcon(name,icon=''){const normalized=String(icon||'').trim(),upstream=/^https?:/i.test(normalized)?normalized:normalized?`${HAKUSH_UI}/${normalized.replace(/\.webp$/i,'')}.webp`:'';return itemIcon(name,upstream)}
function sectionName(app){return app.querySelector('.segmented button.active')?.textContent?.trim().toLowerCase()||'build'}
function targetSummary(profile){const targets=statTargets(profile,{});return[['CRIT Rate',targets.cr],['CRIT DMG',targets.cd],['Energy Recharge',targets.er],['Elemental Mastery',targets.em]].filter(([,t])=>t.great>0)}

async function loadReference(character,detail){if(activeCharacter===character.name&&reference)return reference;activeCharacter=character.name;reference=detail?.raw?.hp?detail.raw:await loadCharacterReference(character);return reference}

function profileMarkup(character,detail,profile,ref){const voices=extractVoiceActors(detail),ratings=roleRatings(profile,detail,ref),region=String(character.region||detail.region||'—').replace('Snezhnaya / Fatui','Snezhnaya'),rarity=safeCharacterRarity(detail?.raw?.rarity??detail?.raw?.rank??detail?.rarity,character?.rarity);return`<section class="section card hotaru-reference-card"><div class="section-head"><div><div class="eyebrow">Character profile</div><h2>${esc(character.name)}</h2></div><span class="pill">${rarity}★</span></div><div class="hotaru-profile-grid"><div><strong>Element</strong><span>${esc(character.element)}</span></div><div><strong>Weapon</strong><span>${esc(character.weapon)}</span></div><div><strong>Region</strong><span>${esc(region)}</span></div><div><strong>Role</strong><span>${esc(profile.role)}</span></div>${voices.slice(0,4).map(v=>`<div><strong>${esc(v.label)} voice</strong><span>${esc(v.name)}</span></div>`).join('')}</div><div class="hotaru-role-rating-grid">${ratings.map(r=>`<div><span>${esc(r.label)}</span><strong>${esc(r.rating)}</strong></div>`).join('')}</div><p class="muted small">Role ratings are Hotaru's kit-based guidance, not an official HoYoverse tier list.</p></section>`}

function statsMarkup(ref){const lv20=referenceStats(ref,20),lv90=referenceStats(ref,90);if(!lv20.length&&!lv90.length)return'';const rows=keys=>keys.map(s=>`<div class="hotaru-stat-row"><span>${esc(s.label)}</span><strong>${esc(s.value)}</strong></div>`).join('');return`<section class="section card hotaru-reference-card"><div class="section-head"><h2>Character stats</h2><div class="hotaru-guide-toggle"><button class="active" data-hotaru-stat-level="20">Lv. 20</button><button data-hotaru-stat-level="90">Lv. 90</button></div></div><div class="hotaru-stat-panel" data-hotaru-stat-panel="20">${rows(lv20)}</div><div class="hotaru-stat-panel" data-hotaru-stat-panel="90" hidden>${rows(lv90)}</div></section>`}

function talentPriorityMarkup(detail,ref,profile){const priority=talentPriority(detail,ref,profile);return`<section class="section card hotaru-reference-card"><div class="section-head"><h2>Talent priority</h2><span class="pill gray">Hotaru guidance</span></div><div class="hotaru-priority-grid">${priority.map(x=>`<div><b>${x.priority}${x.priority===1?'st':x.priority===2?'nd':'rd'}</b><strong>${esc(x.label)}</strong><span>${esc(x.name)}</span></div>`).join('')}</div><p class="muted small">Priority is inferred from kit emphasis and role. Constellations or niche rotations can change the order.</p></section>`}

function constellationMarkup(detail,ref){const list=constellationList(detail,ref);if(!list.length)return'';return`<section class="section card hotaru-reference-card"><div class="section-head"><h2>Constellations</h2><span class="pill gray">C1–C6</span></div><div class="hotaru-constellation-list">${list.map(c=>`<details ${c.index===1?'open':''}><summary><span>C${c.index}</span><strong>${esc(c.name)}</strong><b>${'★'.repeat(constellationRating(c))}${'☆'.repeat(3-constellationRating(c))}</b></summary><p>${esc(c.description)}</p></details>`).join('')}</div><p class="muted small">Constellation star ratings are Hotaru pull-value heuristics, not official ratings.</p></section>`}

async function weaponMarkup(character,profile,catalog){if(!weaponPromise)weaponPromise=hydrateWeaponCandidates(character,12).catch(()=>[]);const hydrated=await weaponPromise,ranked=rankWeapons(hydrated.length?hydrated:(catalog.weapons||[]).filter(w=>w.weapon===character.weapon),profile).slice(0,8);if(!ranked.length)return'';return`<section class="section card hotaru-reference-card"><div class="section-head"><div><div class="eyebrow">Ranked for this build</div><h2>Recommended weapons</h2></div><span class="pill">${esc(character.weapon)}</span></div><div class="hotaru-guide-list">${ranked.map((w,i)=>`<article class="hotaru-guide-row"><div class="hotaru-guide-rank">${i+1}</div>${weaponIcon(w)}<div class="hotaru-guide-copy"><strong>${esc(w.name)}</strong><span>${Number(w.rarity)||1}★ · ${esc(w.subStat||'Stat varies')} · ${esc(weaponAcquisition(w))}</span>${w.passiveDesc||w.description?`<p>${esc(stripMarkup(w.passiveDesc||w.description).slice(0,240))}${stripMarkup(w.passiveDesc||w.description).length>240?'…':''}</p>`:''}</div><div class="score-badge">${Number(w.hotaruScore)||0}</div></article>`).join('')}</div></section>`}

function artifactMarkup(profile,catalog){const ranked=rankArtifactSets(catalog.artifacts||[],profile).slice(0,6);if(!ranked.length)return'';return`<section class="section card hotaru-reference-card"><div class="section-head"><h2>Artifacts ranked</h2><span class="pill warn">Fit score</span></div><div class="hotaru-guide-list">${ranked.map((set,i)=>`<article class="hotaru-guide-row"><div class="hotaru-guide-rank">${i+1}</div>${artifactIcon(set)}<div class="hotaru-guide-copy"><strong>${esc(set.name)}</strong>${set.twoPiece?`<p><b>2-Pc:</b> ${esc(stripMarkup(set.twoPiece))}</p>`:''}${set.fourPiece?`<p><b>4-Pc:</b> ${esc(stripMarkup(set.fourPiece).slice(0,320))}${stripMarkup(set.fourPiece).length>320?'…':''}</p>`:''}</div><div class="score-badge">${Number(set.hotaruScore)||0}</div></article>`).join('')}</div></section>`}

function goalsMarkup(profile){return`<section class="section card hotaru-reference-card"><div class="section-head"><h2>Goal stat values</h2><span class="pill gray">Build dependent</span></div><div class="hotaru-goal-table">${targetSummary(profile).map(([name,t])=>`<div><strong>${esc(name)}</strong><span>Minimum ${t.min}${t.unit} · Good ${t.good}${t.unit} · Great ${t.great}${t.unit}</span></div>`).join('')}</div><p class="muted small">Energy Recharge changes with team batteries, Favonius procs, rotations, and weapon choice. Build Check applies team context separately.</p></section>`}

function buildVariantsMarkup(profile){const variants=guideBuildVariants(profile);return`<section class="section card hotaru-reference-card"><div class="section-head"><h2>Build variants</h2><span class="pill">${variants.length}</span></div><div class="hotaru-variant-grid">${variants.map((v,i)=>`<div><strong>${i===0?'Primary · ':''}${esc(v.name)}</strong><p>${esc(v.note)}</p></div>`).join('')}</div></section>`}

function teamsMarkup(detail,catalog){const teams=sampleTeams(detail,catalog),mates=notableTeammates(detail,catalog),reviewed=teams.some(team=>team.reviewed);if(!teams.length&&!mates.length)return'';return`<section class="section card hotaru-reference-card"><div class="section-head"><div><h2>Team comps</h2><p class="muted small hotaru-team-count">${teams.length} complete variation${teams.length===1?'':'s'} available</p></div><span class="pill ${reviewed?'good':'gray'}">${reviewed?'Reviewed theorycraft':'Hotaru templates'}</span></div>${teams.length?`<div class="hotaru-team-list">${teams.map(team=>`<div class="hotaru-team-block"><div class="hotaru-team-title"><strong>${esc(team.name)}</strong><span class="pill ${team.reviewed?'good':'gray'}">${team.reviewed?'Reviewed':'Template'}</span></div><div class="hotaru-team-grid">${team.members.slice(0,4).map(member=>`<div>${characterIcon(member)}<b>${esc(member.name)}</b><span>${esc(member.role||'Flex')}</span></div>`).join('')}</div>${team.why?`<p class="hotaru-team-why">${esc(team.why)}</p>`:''}</div>`).join('')}</div>`:''}${mates.length?`<div class="hotaru-notable"><h3>Notable teammates</h3>${mates.map(m=>`<div class="hotaru-notable-row">${characterIcon(m)}<div class="hotaru-notable-copy"><strong>${esc(m.name)} · ${esc(m.archetype)}</strong><p>${esc(m.explanation)}</p></div></div>`).join('')}</div>`:''}<p class="muted small">Reviewed teams come from Hotaru's sourced team library. Other sample archetypes are Hotaru templates rather than an official HoYoverse ranking. Adjust for ownership, sustain, energy, and encounter needs.</p></section>`}

function materialRows(items=[]){return items.map(item=>`<div class="list-row hotaru-guide-material-row">${materialIcon(item.name,item.icon)}<div class="row-main"><div class="row-title">${esc(item.name)}</div><div class="row-sub">${Number(item.count||0).toLocaleString()} needed</div></div><button class="ghost" data-hotaru-material="${esc(materialSourceNames(item.name,{count:item.count})[0]||item.name)}">Map</button></div>`).join('')}
function materialSummaryMarkup(detail){const asc=ascensionTotals(detail),tal=talentTotals(detail,9,3),schedule=inferTalentBookSchedule(tal);return`<section class="section card hotaru-reference-card"><div class="section-head"><h2>Material summary</h2><span class="pill gray">With icons</span></div><div class="hotaru-material-columns"><div><h3>Ascension</h3>${materialRows(asc)}</div><div><h3>Talents</h3>${materialRows(tal)}</div></div><div class="notice info"><strong>${esc(schedule.series||'Talent books')}</strong> · ${esc(schedule.days)} · ${esc(schedule.domain)}</div></section>`}
function ascensionBreakdownMarkup(detail){const stages=ascensionStages(detail);if(!stages.length)return'';return`<section class="section card hotaru-reference-card"><div class="section-head"><h2>Ascension by level</h2><span class="pill gray">Exact stages</span></div><div class="hotaru-ascension-stages">${stages.map(stage=>`<div><strong>${esc(stage.label)}</strong><div>${stage.materials.map(item=>`<span>${itemIcon(item.name,item.icon)}<b>${esc(item.name)}</b> ×${Number(item.count||0).toLocaleString()}</span>`).join('')}</div></div>`).join('')}</div></section>`}
function talentScheduleMarkup(detail){const items=talentTotals(detail,9,3),schedule=inferTalentBookSchedule(items);if(!items.length)return'';const books=items.filter(x=>/^(Teachings|Guide|Philosophies) of /i.test(x.name)),others=items.filter(x=>!books.includes(x)&&!/Mora|Crown of Insight/i.test(x.name));return`<section class="section card hotaru-reference-card"><div class="section-head"><h2>Talent level-up materials</h2><span class="pill">${esc(schedule.days)}</span></div><div class="hotaru-material-source-grid"><div><strong>Daily Domain Drops</strong><span>${esc(schedule.domain)}</span>${materialRows(books)}</div><div><strong>Enemy / Weekly Drops</strong>${materialRows(others)}</div></div></section>`}
function explorationMarkup(character){const region=character.region||'Current region',markers=guideExplorationMarkers(region);return`<section class="section card hotaru-reference-card"><div class="section-head"><div><div class="eyebrow">Exploration shortcuts</div><h2>${esc(region)} guide</h2></div><span class="pill gray">Interactive map</span></div><div class="hotaru-exploration-grid">${markers.map(item=>`<button class="secondary" data-hotaru-material="${esc(item.name)}">${esc(item.label)}</button>`).join('')}</div><p class="muted small">Hotaru uses one verified map-marker registry shared with the Interactive Map. Nation-specific Oculus shortcuts are shown only when that mapping is known; Hotaru does not infer them from a character's element.</p></section>`}

async function renderOverview(app,character,detail,profile,ref){const wrap=document.createElement('div');wrap.id='hotaru-deep-guide';wrap.dataset.section='overview';wrap.innerHTML=profileMarkup(character,detail,profile,ref)+statsMarkup(ref)+talentPriorityMarkup(detail,ref,profile)+constellationMarkup(detail,ref);insertBeforeActions(app,wrap)}
async function renderBuild(app,character,detail,profile,catalog){const wrap=document.createElement('div');wrap.id='hotaru-deep-guide';wrap.dataset.section='build';wrap.innerHTML=buildVariantsMarkup(profile)+goalsMarkup(profile)+artifactMarkup(profile,catalog)+teamsMarkup(detail,catalog);insertBeforeActions(app,wrap);const weapon=await weaponMarkup(character,profile,catalog);if(weapon&&!wrap.querySelector('[data-hotaru-weapons-loaded]')){const holder=document.createElement('div');holder.dataset.hotaruWeaponsLoaded='1';holder.innerHTML=weapon;wrap.prepend(holder)}}
async function renderMaterials(app,character,detail){const wrap=document.createElement('div');wrap.id='hotaru-deep-guide';wrap.dataset.section='materials';wrap.innerHTML=materialSummaryMarkup(detail)+ascensionBreakdownMarkup(detail)+talentScheduleMarkup(detail)+explorationMarkup(character);insertBeforeActions(app,wrap)}

export async function enhanceReferenceGuide({app,catalog,detail,character,profile}){
  if(!app||!catalog||!detail||!character||!profile)return;
  const section=sectionName(app),existing=document.getElementById('hotaru-deep-guide');if(existing?.dataset.section===section&&existing?.dataset.character===character.name)return;existing?.remove();
  if(activeCharacter!==character.name){weaponPromise=null;reference=null;activeCharacter=''}
  const ref=await loadReference(character,detail);if(section==='overview')await renderOverview(app,character,detail,profile,ref||{});else if(section==='materials')await renderMaterials(app,character,detail);else await renderBuild(app,character,detail,profile,catalog);
  const rendered=document.getElementById('hotaru-deep-guide');if(rendered)rendered.dataset.character=character.name;
}

document.addEventListener('click',event=>{const button=event.target.closest('[data-hotaru-stat-level]');if(!button)return;const card=button.closest('.hotaru-reference-card');if(!card)return;const level=button.dataset.hotaruStatLevel;card.querySelectorAll('[data-hotaru-stat-level]').forEach(x=>x.classList.toggle('active',x===button));card.querySelectorAll('[data-hotaru-stat-panel]').forEach(panel=>panel.hidden=panel.dataset.hotaruStatPanel!==level)},false);
