import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { associationToRegion, affiliationsFor, enrichCharacterTaxonomy, getRegionOptions } from '../js/features/taxonomy.js';
import { buildMapUrl, normalizeMarkerNames, normalizeTarget, remainingTarget } from '../js/features/interactive-map.js';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
assert.equal(associationToRegion('ASSOC_TYPE_NATLAN'),'Natlan');
assert.equal(associationToRegion('ASSOC_TYPE_NODKRAI'),'Nod-Krai');
assert.ok(affiliationsFor('Arlecchino').includes('Fatui Harbinger'));
assert.ok(affiliationsFor('Arlecchino').includes('House of the Hearth'));
assert.ok(affiliationsFor('Mona').includes('Hexenzirkel-related'));
const enriched=enrichCharacterTaxonomy({id:'100',name:'Example',region:''},{100:'Fontaine'});assert.equal(enriched.region,'Fontaine');
assert.deepEqual(getRegionOptions([{region:'Nod-Krai'},{region:'Mondstadt'}]),['Mondstadt','Nod-Krai']);
assert.deepEqual(normalizeMarkerNames(['Sakura Bloom','Sakura Bloom',' Qingxin ']),['Sakura Bloom','Qingxin']);
const url=buildMapUrl(['Sakura Bloom','Qingxin']);assert.match(url,/genshin-impact-map\.appsample\.com/);assert.equal(new URL(url).searchParams.get('names'),'Sakura Bloom,Qingxin');
const target=normalizeTarget({name:'Lakelight Lily',needed:168,owned:74});assert.equal(remainingTarget(target),94);assert.equal(target.complete,false);
for(const file of ['enhancements.js','enhancements.css','js/features/taxonomy.js','js/features/interactive-map.js'])assert.ok(fs.existsSync(path.join(root,file)),`missing ${file}`);
const enhancement=fs.readFileSync(path.join(root,'enhancements.js'),'utf8');assert.match(enhancement,/filter-region/);assert.match(enhancement,/filter-affiliation/);assert.match(enhancement,/loading="lazy"/);assert.match(enhancement,/data-hotaru-material/);
console.log('Hotaru enhancements QA: all deterministic/static tests passed.');
